### ISSUE TITLE
Issue with spritebatch when drawing the aura for the first time on some characters.

### ISSUE THREAD

**Issue by NuovaPrime** [NuovaPrime/DBT-Issues#5]
**Describe the bug**
Not completely sure, but it just errors for some.

**Screenshots**
`[05:59:22] [1/WARN] [tML]: Silently Caught Exception: 
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Texture2D'.
   at Microsoft.Xna.Framework.Helpers.CheckDisposed(Object obj, IntPtr pComPtr)
   at Microsoft.Xna.Framework.Graphics.TextureCollection.set_Item(Int32 index, Texture value)
   at Microsoft.Xna.Framework.Graphics.SpriteBatch.RenderBatch(Texture2D texture, SpriteInfo[] sprites, Int32 offset, Int32 count)
   at Microsoft.Xna.Framework.Graphics.SpriteBatch.InternalDraw(Texture2D texture, Vector4& destination, Boolean scaleDestination, Nullable1& sourceRectangle, Color color, Single rotation, Vector2& origin, SpriteEffects effects, Single depth)
   at DBT.Builders.Aura.AuraEffect.Draw(DBTPlayer dbtPlayer) in DBT\Builders\Aura\AuraEffect.cs:line 68`

**Comment by Tyndareus** [comment]
Fixed
